# Generated by Django 2.0.8 on 2018-11-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thing',
            new_name='Place',
        ),
    ]
